(()=>{'use strict';
const $=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=d=>d?new Date(d).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}):'—',config=window.AB_SUPABASE_CONFIG||{},auth=config.url&&config.anonKey&&window.supabase?window.supabase.createClient(config.url,config.anonKey):null;
const statuses={NEW:'Nouvelle demande',IN_REVIEW:'En analyse',REPORT_READY:'Rapport prêt',TO_VALIDATE:'À valider',SENT:'Envoyé',CLOSED:'Terminé'},objectives={obtenir_plus_de_clients:'Obtenir plus de clients',ameliorer_visibilite:'Améliorer ma visibilité',moderniser_image:'Moderniser mon image',ameliorer_site:'Améliorer mon site',mieux_apparaitre_google:'Mieux apparaître sur Google',developper_reseaux:'Développer mes réseaux sociaux',vendre_en_ligne:'Vendre en ligne',outils_numeriques:'Mettre en place des outils numériques',autre:'Autre'},problems={peu_visible:'Entreprise peu visible',site_inadapte:'Site inadapté',manque_clients:'Peu de clients issus du numérique',reseaux_inactifs:'Réseaux sociaux peu actifs',image_vieillissante:'Image numérique vieillissante',difficile_a_gerer:'Outils difficiles à gérer',aucune_presence:'Aucune présence numérique',autre:'Autre'},networks={website:'Site internet',google:'Google / Google Maps',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',linkedin:'LinkedIn',other:'Autre présence'};
let rows=[],current=null,activeTab='overview';
async function api(url,options={}){if(!auth)throw new Error('Configuration Supabase indisponible.');const{data:{session},error}=await auth.auth.getSession();if(error||!session?.access_token){showLogin();throw new Error('Connectez-vous avec votre compte administrateur.')}const response=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{}),authorization:`Bearer ${session.access_token}`}}),data=response.headers.get('content-type')?.includes('json')?await response.json():null;if(response.status===401||response.status===403){if(response.status===403)await auth.auth.signOut({scope:'local'});showLogin();throw new Error(response.status===403?'Ce compte n’est pas autorisé.':'Votre session a expiré.')}if(!response.ok)throw new Error(data?.error||'Opération impossible.');return data}
function setError(message=''){$('#auditError').textContent=message}
function badge(status){return `<span class="badge ${esc(status)}">${esc(statuses[status]||status)}</span>`}
function showLogin(){$('#auditApp').classList.add('hidden');$('#loginBox').classList.remove('hidden');$('#refresh').classList.add('hidden');$('#logout').classList.add('hidden');$('#adminName').textContent=''}
function showApp(email){$('#loginBox').classList.add('hidden');$('#auditApp').classList.remove('hidden');$('#refresh').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#adminName').textContent=email}
async function init(){if(!auth){$('#loginError').textContent='Configuration Supabase indisponible.';return}try{const{data:{session}}=await auth.auth.getSession();if(!session){showLogin();return}const identity=await api('/api/admin/session');showApp(identity.email);await load()}catch(error){showLogin();if(error.message.includes('pas autorisé'))$('#loginError').textContent=error.message}}
async function login(){try{$('#loginError').textContent='';$('#login').disabled=true;if(!auth)throw new Error('Configuration Supabase indisponible.');const{error}=await auth.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)throw new Error('Identifiants incorrects.');const identity=await api('/api/admin/session');showApp(identity.email);$('#password').value='';await load()}catch(error){$('#loginError').textContent=error.message}finally{$('#login').disabled=false}}
async function load(){try{setError();const params=new URLSearchParams();if($('#auditSearch').value)params.set('q',$('#auditSearch').value);if($('#auditStatus').value)params.set('status',$('#auditStatus').value);const data=await api('/api/admin/audits?'+params);rows=data.audits||[];renderMetrics();renderList();const reference=new URLSearchParams(location.search).get('reference');if(reference&&!current){const match=rows.find(r=>r.reference===reference);if(match)await show(match.id)}}catch(error){setError(error.message)}}
function renderMetrics(){const definitions=Object.entries(statuses);$('#auditMetrics').innerHTML=definitions.map(([status,label])=>`<div class="metric"><b>${rows.filter(r=>r.status===status).length}</b><span>${label}</span></div>`).join('')}
function renderList(){const selected=current?.audit?.id;$('#auditList').innerHTML=rows.length?rows.map(r=>`<button class="request ${selected===r.id?'active':''}" data-audit="${r.id}"><div class="request-head"><b>${esc(r.reference)}</b>${badge(r.status)}</div><small>${esc(r.first_name)} ${esc(r.last_name)} · ${esc(r.company_name)}</small><small>${esc(r.email)} · ${fmt(r.submitted_at)}</small></button>`).join(''):'<div class="empty">Aucun audit pour ces filtres.</div>';document.querySelectorAll('[data-audit]').forEach(button=>button.onclick=()=>show(button.dataset.audit))}
async function show(id){try{setError();$('#auditDetail').innerHTML='<div class="empty">Chargement du dossier…</div>';current=await api(`/api/admin/audits/${encodeURIComponent(id)}`);history.replaceState(null,'',`${location.pathname}?reference=${encodeURIComponent(current.audit.reference)}`);renderList();renderDetail()}catch(error){setError(error.message)}}
function info(label,value,long=false){return `<div class="${long?'audit-info-long':''}"><div class="info"><b>${esc(label)}</b>${esc(String(value??'').trim()||'—')}</div></div>`}
function safeLink(url){try{const parsed=new URL(url);return['http:','https:'].includes(parsed.protocol)?parsed.toString():''}catch{return''}}
function nextAction(status){return({NEW:'Commencer l’analyse',IN_REVIEW:'Finaliser les constats',REPORT_READY:'Vérifier le futur rapport',TO_VALIDATE:'Valider le rapport',SENT:'Suivre le retour du client',CLOSED:'Dossier terminé'}[status]||'Examiner le dossier')}
function renderDetail(){const a=current.audit,failed=current.notifications.filter(n=>n.status==='failed').length,pdf=current.documents.find(d=>d.document_type==='request_summary');$('#auditDetail').innerHTML=`<div class="detail-head"><div><h2>${esc(a.reference)}</h2><div class="identity-line">${esc(a.first_name)} ${esc(a.last_name)} · ${esc(a.company_name)} · ${esc(a.email)}</div></div><div class="status-row"><select id="auditStatusSelect">${Object.entries(statuses).map(([key,label])=>`<option value="${key}" ${a.status===key?'selected':''}>${label}</option>`).join('')}</select><button id="saveAuditStatus" class="primary">Enregistrer</button></div></div><section class="commercial-overview"><div class="summary-card"><span>Client</span><b>${esc(a.first_name)} ${esc(a.last_name)}</b><small>${esc(a.email)}</small></div><div class="summary-card"><span>Demande</span><b>${esc(objectives[a.main_objective]||a.main_objective)}</b><small>${esc(a.activity)}</small></div><div class="summary-card"><span>Traitement</span>${badge(a.status)}</div><div class="summary-card next-card"><span>Prochaine action</span><b>${esc(nextAction(a.status))}</b></div><div class="summary-card"><span>E-mails</span><b>${current.notifications.filter(n=>n.status==='sent').length} envoyé(s)</b><small>${failed?`${failed} en échec`:'Aucun échec'}</small></div><div class="summary-card"><span>PDF</span><b>${pdf?'Disponible':'À générer'}</b>${pdf?`<small>${esc(pdf.filename)}</small>`:''}</div></section><div class="audit-actions">${pdf?`<a class="secondary" target="_blank" rel="noopener" href="/api/admin/audits/${a.id}/pdf">Ouvrir le PDF</a>`:''}</div><nav class="tabs">${[['overview','Demande complète'],['notifications','E-mails'],['notes','Notes internes'],['history','Statuts'],['future','Rapport futur']].map(([id,label])=>`<button class="tab ${activeTab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</nav><div id="auditTab" class="tab-panel"></div>`;$('#saveAuditStatus').onclick=saveStatus;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{activeTab=button.dataset.tab;renderDetail()});renderTab()}
function renderTab(){const panel=$('#auditTab'),a=current.audit;if(activeTab==='overview'){const presence=Object.entries(a.digital_presence||{}).filter(([,v])=>v?.present);panel.innerHTML=`<section class="audit-answer-section"><h3>Client et coordonnées</h3><div class="info-grid">${info('Prénom',a.first_name)}${info('Nom',a.last_name)}${info('E-mail',a.email)}${info('Téléphone',a.phone)}${info('Date',fmt(a.submitted_at))}${info('Référence',a.reference)}</div></section><section class="audit-answer-section"><h3>Entreprise et activité</h3><div class="info-grid">${info('Entreprise / organisation',a.company_name)}${info('Activité / secteur',a.activity)}${info('Ville / zone',a.city)}${info('Description',a.company_description,true)}</div></section><section class="audit-answer-section"><h3>Présence numérique</h3><div class="audit-presence">${presence.length?presence.map(([key,value])=>{const url=safeLink(value.url);return `<div class="audit-link"><b>${esc(networks[key]||key)}</b>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(url)}</a>`:'<span class="muted">Présence déclarée, sans URL</span>'}</div>`}).join(''):'<div class="empty">Aucune présence numérique déclarée.</div>'}</div></section><section class="audit-answer-section"><h3>Objectif et difficulté</h3><div class="info-grid">${info('Objectif principal',objectives[a.main_objective]||a.main_objective)}${info('Précisions sur l’objectif',a.objective_details,true)}${info('Problème principal',problems[a.main_problem]||a.main_problem)}${info('Explications',a.problem_details,true)}${info('Informations complémentaires',a.additional_information,true)}</div></section>`}
else if(activeTab==='notifications'){panel.innerHTML=current.notifications.map(n=>`<div class="audit-notification"><div><b>${n.notification_type==='admin'?'Notification A&B':'Confirmation client'} ${badge(n.status)}</b><small>${esc(n.recipient)} · ${n.provider?esc(n.provider):'fournisseur en attente'} · ${n.attempt_count} tentative(s)</small>${n.error_message?`<p class="error">${esc(n.error_message)}</p>`:''}</div>${n.status==='failed'?`<button class="primary" data-retry="${n.id}">Réessayer</button>`:''}${n.status==='unknown'?'<span class="muted">Vérification manuelle requise</span>':''}</div>`).join('')||'<div class="empty">Aucune notification.</div>';document.querySelectorAll('[data-retry]').forEach(button=>button.onclick=()=>retry(button.dataset.retry))}
else if(activeTab==='notes'){panel.innerHTML=`<div class="audit-note-form"><textarea id="auditNote" placeholder="Nouvelle note strictement interne…"></textarea><button id="addAuditNote" class="primary">Ajouter</button></div>${current.notes.map(n=>`<div class="answer"><small>${fmt(n.created_at)} · ${esc(n.author)}</small><div>${esc(n.note)}</div></div>`).join('')||'<div class="empty">Aucune note interne.</div>'}`;$('#addAuditNote').onclick=addNote}
else if(activeTab==='history')panel.innerHTML=current.history.map(h=>`<div class="answer"><b>${esc(statuses[h.old_status]||h.old_status||'Création')} → ${esc(statuses[h.new_status]||h.new_status)}</b><small>${fmt(h.created_at)}${h.actor?` · ${esc(h.actor)}`:''}</small></div>`).join('')||'<div class="empty">Aucun historique.</div>';
else panel.innerHTML='<div class="actions-box future-actions"><h3>Préparation du futur rapport d’audit</h3><p>La base est prête à recevoir des constats, priorités, recommandations et preuves. Ces actions seront activées lors de la phase rapport.</p><div class="actions"><button class="action" disabled>Ajouter un constat</button><button class="action" disabled>Générer le rapport</button><button class="action" disabled>Prévisualiser</button><button class="action" disabled>Valider</button><button class="action" disabled>Envoyer au client</button></div></div>'}
async function saveStatus(){const status=$('#auditStatusSelect').value;if(!confirm(`Confirmer le statut « ${statuses[status]} » ?`))return;try{await api(`/api/admin/audits/${current.audit.id}`,{method:'PATCH',body:JSON.stringify({status})});await show(current.audit.id);await load()}catch(error){setError(error.message)}}
async function addNote(){const note=$('#auditNote').value.trim();if(!note)return;try{await api(`/api/admin/audits/${current.audit.id}/notes`,{method:'POST',body:JSON.stringify({note})});await show(current.audit.id)}catch(error){setError(error.message)}}
async function retry(deliveryId){if(!confirm('Réessayer cet envoi ?'))return;try{await api(`/api/admin/audits/${current.audit.id}/retry`,{method:'POST',body:JSON.stringify({deliveryId})});await show(current.audit.id)}catch(error){setError(error.message)}}
async function openPrivatePdf(url){const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const{data:{session}}=await auth.auth.getSession();if(!session)throw new Error('Votre session a expiré.');const response=await fetch(url,{headers:{authorization:`Bearer ${session.access_token}`}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'PDF indisponible.')}const objectUrl=URL.createObjectURL(await response.blob());if(tab)tab.location.href=objectUrl;else window.location.href=objectUrl;setTimeout(()=>URL.revokeObjectURL(objectUrl),60000)}catch(error){tab?.close();setError(error.message)}}
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="/api/admin/audits/"][href$="/pdf"]');if(!link)return;event.preventDefault();openPrivatePdf(link.href)});
$('#login').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#logout').onclick=async()=>{await auth?.auth.signOut({scope:'local'});location.reload()};$('#refresh').onclick=load;let timer;$('#auditSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,250)};$('#auditStatus').onchange=load;$('#auditClear').onclick=()=>{$('#auditSearch').value='';$('#auditStatus').value='';load()};init();
})();
