(()=>{'use strict';
const DRAFT_KEY='ab-audit-express-draft-v1',STEPS=6,API_BASE=location.hostname.endsWith('github.io')?'https://a-b-technologies.pages.dev':'';
const objectives={obtenir_plus_de_clients:'Obtenir plus de clients',ameliorer_visibilite:'Améliorer ma visibilité',moderniser_image:'Moderniser mon image',ameliorer_site:'Améliorer mon site',mieux_apparaitre_google:'Mieux apparaître sur Google',developper_reseaux:'Développer mes réseaux sociaux',vendre_en_ligne:'Vendre en ligne',outils_numeriques:'Mettre en place des outils numériques',autre:'Autre'};
const problems={peu_visible:'Mon entreprise est peu visible',site_inadapte:'Mon site ne répond plus à mes besoins',manque_clients:'Ma présence numérique apporte peu de clients',reseaux_inactifs:'Mes réseaux sociaux sont peu actifs',image_vieillissante:'Mon image numérique paraît vieillissante',difficile_a_gerer:'Mes outils sont difficiles à gérer',aucune_presence:'Je n’ai pas encore de présence numérique',autre:'Autre'};
const networks={website:'Site internet',google:'Google / Google Maps',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',linkedin:'LinkedIn',other:'Autre présence'};
const empty=()=>({step:0,review:false,submissionId:crypto.randomUUID(),loadedAt:Date.now(),firstName:'',lastName:'',email:'',phone:'',companyName:'',activity:'',city:'',companyDescription:'',digitalPresence:Object.fromEntries(Object.keys(networks).map(k=>[k,{present:false,url:''}])),mainObjective:'',objectiveDetails:'',mainProblem:'',problemDetails:'',additionalInformation:'',consent:false});
const $=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=load(),sending=false;
function load(){try{const saved=JSON.parse(sessionStorage.getItem(DRAFT_KEY));if(saved&&saved.submissionId&&Date.now()-saved.loadedAt<86400000)return{...empty(),...saved,digitalPresence:{...empty().digitalPresence,...saved.digitalPresence}}}catch{}return empty()}
function save(){sessionStorage.setItem(DRAFT_KEY,JSON.stringify(state));$('#saveState').textContent='Brouillon conservé'}
function val(id){return document.getElementById(id)?.value.trim()||''}
function radio(name){return document.querySelector(`input[name="${name}"]:checked`)?.value||''}
function field(id,label,type='text',attrs=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(state[id])}" ${attrs}></div>`}
function render(){const review=state.review;$('#stepCount').textContent=review?'Récapitulatif':`Étape ${state.step+1} sur ${STEPS}`;$('#progressBar').style.width=`${review?100:((state.step+1)/STEPS)*100}%`;$('#previous').classList.toggle('hidden',state.step===0&&!review);$('#next').textContent=review?'Confirmer ma demande d’audit':state.step===STEPS-1?'Voir le récapitulatif':'Suivant';$('#formError').textContent='';$('#stepContent').innerHTML=review?summary():steps[state.step]();wire();$('#stepContent').querySelector('h2')?.focus({preventScroll:true});save()}
const steps=[
()=>`<h2 class="step-title" tabindex="-1">Faisons connaissance.</h2><p class="step-lead">Ces coordonnées nous permettront de confirmer votre demande.</p><div class="fields">${field('firstName','Prénom','text','autocomplete="given-name" required maxlength="100"')}${field('lastName','Nom','text','autocomplete="family-name" required maxlength="100"')}${field('email','Adresse e-mail','email','autocomplete="email" required maxlength="254"')}${field('phone','Téléphone','tel','autocomplete="tel" required maxlength="40" inputmode="tel"')}</div>`,
()=>`<h2 class="step-title" tabindex="-1">Votre activité.</h2><p class="step-lead">Entreprise, association, indépendant : décrivez simplement votre cadre de travail.</p><div class="fields">${field('companyName','Entreprise / organisation','text','required maxlength="180"')}${field('activity','Activité / secteur','text','required maxlength="180"')}${field('city','Ville ou zone d’activité','text','maxlength="180"')}<div class="field full"><label for="companyDescription">Courte description <span class="hint">(facultatif)</span></label><textarea id="companyDescription" maxlength="1500">${esc(state.companyDescription)}</textarea></div></div>`,
()=>`<h2 class="step-title" tabindex="-1">Votre présence numérique actuelle.</h2><p class="step-lead">Indiquez uniquement les canaux que vous utilisez déjà.</p><div class="presence-list">${Object.entries(networks).map(([key,label])=>{const item=state.digitalPresence[key]||{};return `<div class="presence-card"><div class="presence-head"><strong>${label}</strong><div class="yes-no"><label><input type="radio" name="presence-${key}" value="yes" ${item.present?'checked':''}> Oui</label><label><input type="radio" name="presence-${key}" value="no" ${!item.present?'checked':''}> Non</label></div></div>${item.present?`<div class="presence-url"><label class="group-label" for="url-${key}">Adresse ${key==='website'?'(obligatoire)':'(facultative)'}</label><input id="url-${key}" type="url" inputmode="url" placeholder="https://" value="${esc(item.url)}" ${key==='website'?'required':''} maxlength="500"></div>`:''}</div>`}).join('')}</div>`,
()=>`<h2 class="step-title" tabindex="-1">Votre objectif principal.</h2><p class="step-lead">Choisissez ce qui compte le plus pour votre activité aujourd’hui.</p><div class="choice-grid">${Object.entries(objectives).map(([key,label])=>`<label class="choice"><input type="radio" name="mainObjective" value="${key}" ${state.mainObjective===key?'checked':''}><span>${label}</span></label>`).join('')}</div>${state.mainObjective==='autre'?`<div class="field" style="margin-top:16px"><label for="objectiveDetails">Précisez votre objectif</label><textarea id="objectiveDetails" maxlength="1000" required>${esc(state.objectiveDetails)}</textarea></div>`:''}`,
()=>`<h2 class="step-title" tabindex="-1">Votre difficulté actuelle.</h2><p class="step-lead">Aucun terme technique n’est nécessaire : choisissez la situation la plus proche de la vôtre.</p><div class="choice-grid">${Object.entries(problems).map(([key,label])=>`<label class="choice"><input type="radio" name="mainProblem" value="${key}" ${state.mainProblem===key?'checked':''}><span>${label}</span></label>`).join('')}</div><div class="field" style="margin-top:16px"><label for="problemDetails">Expliquez-nous avec vos mots <span class="hint">(facultatif)</span></label><textarea id="problemDetails" maxlength="2000">${esc(state.problemDetails)}</textarea></div>`,
()=>`<h2 class="step-title" tabindex="-1">Une dernière précision ?</h2><p class="step-lead">Ajoutez seulement ce qui peut nous aider à mieux comprendre votre demande.</p><div class="field"><label for="additionalInformation">Y a-t-il quelque chose que vous souhaitez nous préciser ? <span class="hint">(facultatif)</span></label><textarea id="additionalInformation" maxlength="3000">${esc(state.additionalInformation)}</textarea></div>`
];
function summary(){const presence=Object.entries(state.digitalPresence).filter(([,v])=>v.present).map(([k,v])=>`${networks[k]}${v.url?` — ${v.url}`:''}`).join('\n')||'Aucune présence numérique déclarée';return `<h2 class="step-title" tabindex="-1">Vérifiez votre demande.</h2><p class="step-lead">Aucune donnée n’est encore envoyée. Vous pouvez modifier chaque section.</p><div class="summary"><article><button class="summary-edit" data-edit="0" type="button">Modifier</button><h3>Vos coordonnées</h3><p>${esc(`${state.firstName} ${state.lastName}\n${state.email}\n${state.phone}`)}</p></article><article><button class="summary-edit" data-edit="1" type="button">Modifier</button><h3>Votre activité</h3><p>${esc(`${state.companyName}\n${state.activity}${state.city?` — ${state.city}`:''}${state.companyDescription?`\n${state.companyDescription}`:''}`)}</p></article><article><button class="summary-edit" data-edit="2" type="button">Modifier</button><h3>Votre présence numérique</h3><p>${esc(presence)}</p></article><article><button class="summary-edit" data-edit="3" type="button">Modifier</button><h3>Votre objectif</h3><p>${esc(`${objectives[state.mainObjective]||'Non renseigné'}${state.objectiveDetails?`\n${state.objectiveDetails}`:''}`)}</p></article><article><button class="summary-edit" data-edit="4" type="button">Modifier</button><h3>Vos réponses</h3><p>${esc(`${problems[state.mainProblem]||'Non renseigné'}${state.problemDetails?`\n${state.problemDetails}`:''}${state.additionalInformation?`\n\nPrécision : ${state.additionalInformation}`:''}`)}</p></article></div><label class="consent"><input id="consent" type="checkbox" ${state.consent?'checked':''}><span>Je confirme que ces informations peuvent être utilisées par A&amp;B Technologies pour analyser et traiter ma demande d’Audit Express.</span></label>`}
function collect(){if(state.review){state.consent=$('#consent')?.checked===true;save();return}switch(state.step){case 0:Object.assign(state,{firstName:val('firstName'),lastName:val('lastName'),email:val('email'),phone:val('phone')});break;case 1:Object.assign(state,{companyName:val('companyName'),activity:val('activity'),city:val('city'),companyDescription:val('companyDescription')});break;case 2:for(const key of Object.keys(networks)){const present=radio(`presence-${key}`)==='yes';state.digitalPresence[key]={present,url:present?val(`url-${key}`):''}}break;case 3:state.mainObjective=radio('mainObjective');state.objectiveDetails=val('objectiveDetails');break;case 4:state.mainProblem=radio('mainProblem');state.problemDetails=val('problemDetails');break;case 5:state.additionalInformation=val('additionalInformation');break}save()}
function validate(){collect();const form=$('#auditForm');if(!form.checkValidity()){form.reportValidity();return'Veuillez vérifier les champs indiqués.'}if(state.step===3&&!state.mainObjective)return'Choisissez votre objectif principal.';if(state.step===4&&!state.mainProblem)return'Choisissez votre difficulté principale.';if(state.step===2){for(const [key,item] of Object.entries(state.digitalPresence)){if(item.url){try{const u=new URL(item.url);if(!['http:','https:'].includes(u.protocol))throw 0}catch{return`Vérifiez l’adresse indiquée pour ${networks[key]}.`}}}}return''}
function wire(){document.querySelectorAll('input,textarea,select').forEach(el=>el.addEventListener('input',collect));document.querySelectorAll('input[type=radio]').forEach(el=>el.addEventListener('change',()=>{collect();if(state.step===2||state.step===3)render()}));document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>{state.review=false;state.step=Number(button.dataset.edit);render()})}
async function next(){if(sending)return;if(state.review){collect();if(!state.consent)return $('#formError').textContent='Votre confirmation est nécessaire avant l’envoi.';return submit()}const error=validate();if(error)return $('#formError').textContent=error;if(state.step===STEPS-1)state.review=true;else state.step++;render()}
function previous(){collect();if(state.review)state.review=false;else if(state.step>0)state.step--;render()}
function cancel(){collect();const hasData=[state.firstName,state.lastName,state.email,state.companyName,state.activity,state.mainProblem].some(Boolean);if(hasData&&!confirm('Abandonner cette demande ? Les réponses de ce brouillon seront effacées.'))return;sessionStorage.removeItem(DRAFT_KEY);location.href='index.html'}
async function submit(){sending=true;$('#next').disabled=true;$('#next').textContent='Enregistrement…';$('#formError').textContent='';try{const response=await fetch(`${API_BASE}/api/audits/submit`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({submissionId:state.submissionId,loadedAt:state.loadedAt,websiteConfirm:$('#websiteConfirm')?.value||'',payload:{firstName:state.firstName,lastName:state.lastName,email:state.email,phone:state.phone,companyName:state.companyName,activity:state.activity,city:state.city,companyDescription:state.companyDescription,digitalPresence:state.digitalPresence,mainObjective:state.mainObjective,objectiveDetails:state.objectiveDetails,mainProblem:state.mainProblem,problemDetails:state.problemDetails,additionalInformation:state.additionalInformation,consent:state.consent}})});const result=await response.json().catch(()=>({}));if(!response.ok||!result.success||!result.reference)throw new Error(result.error||'La demande n’a pas pu être enregistrée.');sessionStorage.removeItem(DRAFT_KEY);$('#auditWizard').classList.add('hidden');$('#auditReference').textContent=result.reference;$('#confirmation').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}catch(error){$('#formError').textContent=error.message||'Une erreur est survenue. Vos réponses sont conservées.';$('#next').disabled=false;$('#next').textContent='Réessayer'}finally{sending=false}}
$('#startAudit').onclick=()=>{$('#auditStart').classList.add('hidden');$('#auditWizard').classList.remove('hidden');render()};$('#next').onclick=next;$('#previous').onclick=previous;$('#cancelAudit').onclick=cancel;$('#auditForm').addEventListener('submit',e=>e.preventDefault());if(sessionStorage.getItem(DRAFT_KEY)){$('#auditStart').querySelector('p:last-of-type')?.insertAdjacentHTML('afterend','<p class="hint">Un brouillon récent a été retrouvé sur cet appareil.</p>')}
})();
