(() => {
  'use strict';
  const DRAFT_KEY = 'ab-project-configurator-v1';
  const MAX_FILE_SIZE = 10 * 1024 * 1024;
  const ALLOWED_TYPES = ['application/pdf','image/jpeg','image/png','image/webp','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
  const $ = (s) => document.querySelector(s);
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const saved = (() => { try { return JSON.parse(localStorage.getItem(DRAFT_KEY)) || {}; } catch { return {}; } })();
  const state = { step: 0, answers: saved.answers || {}, files: [], sending: false };
  const config = window.AB_SUPABASE_CONFIG || {};
  const supabase = config.url && config.anonKey && window.supabase ? window.supabase.createClient(config.url, config.anonKey) : null;

  const opts = {
    organization:['Indépendant','TPE','PME','Association','Commerce','Profession libérale','Startup','Établissement','Particulier','Autre'],
    types:['Création d’un site vitrine','Refonte d’un site','Site e-commerce','Application web','Application mobile','SaaS','Plateforme métier','Marketplace','Réservation','Espace client','Intranet / système interne','Automatisation','Audit numérique','SEO / visibilité Google','Google Business Profile','Réseaux sociaux','Identité numérique','Maintenance / hébergement','Je ne sais pas exactement ce qu’il me faut'],
    objectives:['Présenter mon entreprise','Gagner en crédibilité','Obtenir plus de clients','Générer des demandes de devis','Vendre en ligne','Prendre des rendez-vous','Recevoir des réservations','Fidéliser','Automatiser une tâche','Remplacer une méthode manuelle','Faciliter le travail des employés','Créer une communauté','Informer / former','Recruter','Centraliser des données','Lancer une activité'],
    audience:['Particuliers','Entreprises','Clients actuels','Prospects','Employés','Administrateurs','Partenaires','Étudiants','Enseignants','Professionnels','Institutions','Autre'],
    design:['Moderne','Minimaliste','Professionnel','Institutionnel','Premium','Élégant','Chaleureux','Coloré','Sobre','Technologique','Futuriste','Dynamique','Créatif'],
    pages:['Accueil','À propos','Services','Produits','Tarifs','Portfolio / réalisations','Équipe','Blog / actualités','FAQ','Témoignages','Contact','Rendez-vous','Demande de devis','Boutique','Panier','Espace client','Connexion','Dashboard','Administration','Mentions légales','Confidentialité'],
    features:['Formulaire de contact','Demande de devis','Réservation / rendez-vous','Calendrier','WhatsApp','Comptes utilisateurs','Espace client','Dashboard','Espace administrateur','Recherche et filtres','Notifications email','SMS / WhatsApp','Chat / messagerie','Avis et notation','Upload de fichiers','Génération PDF','Carte / géolocalisation','Paiement','Abonnements','Panier et commandes','Catalogue / stock','Promotions','Newsletter','Blog','Chatbot / IA','Traduction / multilingue','Statistiques','Export Excel / CSV','Connexion Google'],
    data:['Utilisateurs','Clients','Commandes','Rendez-vous','Messages','Produits','Documents','Statistiques','Historique','Autre'],
    integrations:['Google','Google Maps','Google Calendar','WhatsApp','Instagram','Facebook','TikTok','LinkedIn','Stripe','PayPal','Email','CRM','ERP','Comptabilité','API / service existant'],
    seo:['SEO technique','SEO local','Optimisation de contenu','Google Business Profile','Audit de visibilité','Stratégie réseaux sociaux','Optimisation des profils','Suivi analytics'],
    security:['Informations personnelles','Documents privés','Données financières','Paiements','Données professionnelles confidentielles','Données de mineurs','Aucune','Je ne sais pas'],
    maintenance:['Maintenance','Corrections','Mises à jour','Sauvegardes','Support','Ajout de fonctionnalités','Accompagnement','Formation','Je ne sais pas']
  };
  const has = (...values) => values.some(v => (state.answers.request_types || []).includes(v));
  const steps = [
    {id:'identity',title:'Faisons connaissance',lead:'Ces informations nous permettent de vous répondre dans la bonne langue et au bon moment.',fields:[
      ['first_name','Prénom','text',true],['last_name','Nom','text',true],['company_name','Entreprise ou projet','text'],['role','Votre fonction','text'],['activity','Votre activité','text',true],['organization','Type d’organisation','select',true,opts.organization],['country','Pays','text',true],['city','Ville','text'],['phone','Téléphone','tel',true],['whatsapp','WhatsApp','tel'],['email','Email','email',true],['preferred_language','Langue préférée','select',true,['français','anglais','arabe']],['current_site','Site actuel','url'],['social_links','Réseaux sociaux actuels','textarea']]},
    {id:'request',title:'De quoi avez-vous besoin ?',lead:'Vous pouvez sélectionner plusieurs éléments. Nous vous aiderons à faire les bons choix.',choices:['request_types',opts.types,true]},
    {id:'goals',title:'Vos objectifs',lead:'Parlez-nous de la raison du projet avant de parler de la solution.',choices:['objectives',opts.objectives],fields:[['current_problem','Quel problème ce projet doit-il résoudre ?','textarea',true],['current_method','Comment gérez-vous ce sujet aujourd’hui ?','textarea'],['success_definition','Qu’est-ce qui vous ferait dire que le projet est une réussite ?','textarea'],['why_now','Pourquoi lancer ce projet maintenant ?','textarea']]},
    {id:'audience',title:'Les personnes à qui vous vous adressez',lead:'Cela nous aide à concevoir une expérience réellement adaptée.',choices:['audience',opts.audience],fields:[['age_range','Tranche d’âge principale','text'],['regions','Pays ou régions visés','text'],['digital_comfort','Aisance numérique','select',false,['Débutant','Intermédiaire','Très à l’aise','Mixte','Je ne sais pas']],['main_device','Appareil principal','select',false,['Smartphone','Ordinateur','Tablette','Plusieurs','Je ne sais pas']],['audience_needs','Attentes ou contraintes particulières','textarea']]},
    {id:'design',title:'L’univers que vous imaginez',lead:'Il n’y a pas de mauvaise réponse : dites-nous l’impression que vous souhaitez laisser.',choices:['design_style',opts.design],fields:[['desired_feeling','Que souhaitez-vous que les visiteurs ressentent ?','textarea'],['desired_colors','Couleurs souhaitées','text'],['forbidden_colors','Couleurs à éviter','text'],['typography','Style de texte','select',false,['Moderne','Élégant','Traditionnel','Très lisible','Fort','Léger','A&B choisit']],['navigation','Navigation','select',false,['Menu classique en haut','Menu très simple','Menu complet','Menu latéral','A&B choisit']],['density','Quantité d’information','select',false,['Très épuré','Équilibré','Beaucoup d’informations']],['animations','Animations','select',false,['Aucune','Très discrètes','Modérées','Importantes','Je ne sais pas']],['appearance','Apparence','select',false,['Claire','Sombre','Les deux','A&B choisit']]]},
    {id:'references',title:'Vos inspirations',lead:'Ajoutez des sites que vous appréciez, même si vous ne savez pas expliquer pourquoi.',special:'references',fields:[['avoid_style','Y a-t-il un style que vous ne voulez surtout pas ?','textarea']]},
    {id:'structure',title:'Structure et contenu',lead:'Choisissez les pages qui vous semblent utiles. Nous vous conseillerons si nécessaire.',when:() => !has('Audit numérique','SEO / visibilité Google','Google Business Profile','Réseaux sociaux'),choices:['pages',opts.pages],fields:[['pages_advice','Je ne sais pas quelles pages sont nécessaires et souhaite être conseillé','checkbox'],['custom_pages','Pages particulières : nom, objectif et contenu attendu','textarea'],['content_status','Vos contenus (logo, textes, photos, vidéos) sont…','select',false,['Déjà disponibles','Partiellement disponibles','À améliorer','À créer par A&B','Je ne sais pas']],['launch_languages','Langues à prévoir au lancement','text'],['rtl_needed','Une version arabe de droite à gauche est-elle nécessaire ?','select',false,['Oui','Non','Je ne sais pas']]]},
    {id:'features',title:'Fonctionnalités attendues',lead:'Pour chacune, indiquez ce qui est indispensable, souhaité ou peut attendre.',special:'priorities',when:() => !has('Audit numérique','SEO / visibilité Google','Google Business Profile','Réseaux sociaux')},
    {id:'logic',title:'Fonctionnement de votre projet',lead:'Répondez simplement : nous traduirons vos besoins en solution technique.',when:() => !has('Audit numérique','SEO / visibilité Google','Google Business Profile','Réseaux sociaux'),choices:['stored_data',opts.data],fields:[['accounts_needed','Des personnes devront-elles créer un compte ?','select',false,['Oui','Non','Je ne sais pas']],['user_types','Types de personnes et ce qu’elles pourront faire','textarea'],['workflows','Quand quelqu’un fait une action, que doit-il se passer ensuite ? Décrivez un ou plusieurs parcours.','textarea']]},
    {id:'branches',title:'Besoins spécifiques',lead:'Cette étape s’adapte à votre demande.',special:'branches',when:() => has('Site e-commerce','Réservation','Application mobile')},
    {id:'operations',title:'Pilotage, visibilité et sécurité',lead:'Précisez ce que vous souhaitez pouvoir gérer et les services à connecter.',choices:['integrations',opts.integrations],fields:[['self_manage','Après livraison, que souhaitez-vous gérer vous-même ?','textarea'],['infrastructure','Possédez-vous déjà un nom de domaine, hébergement, adresse email pro ou système existant ?','textarea'],['google_visibility','Souhaitez-vous apparaître sur Google ? Zones et mots-clés connus ?','textarea'],['seo_services','Services de visibilité qui vous intéressent','select',false,opts.seo],['security_data','Votre projet traitera-t-il des données sensibles ?','select',false,opts.security],['maintenance','Accompagnement souhaité après livraison','select',false,opts.maintenance]]},
    {id:'budget',title:'Budget, délai et vision',lead:'Ces éléments nous aident à proposer une solution réaliste. Ils ne constituent pas un devis.',fields:[['budget','Enveloppe envisagée','select',true,['Pas encore','Moins de 2 500 DH','2 500 à 5 000 DH','5 000 à 10 000 DH','10 000 à 20 000 DH','20 000 à 50 000 DH','Plus de 50 000 DH','Je préfère en discuter']],['timeline','Délai souhaité','select',true,['Aucune urgence','Moins d’un mois','1 à 3 mois','3 à 6 mois','Plus de 6 mois','Date précise','Je ne sais pas']],['deadline_reason','Si vous avez une date, pourquoi est-elle importante ?','textarea'],['must_have','Ce qui est absolument indispensable','textarea'],['future_features','Ce qui peut attendre ou être prévu pour une version future','textarea'],['vision','Imaginez votre projet terminé exactement comme vous le souhaitez. À quoi ressemble-t-il et que permet-il de faire ?','textarea',true],['consent','J’accepte que mes informations soient traitées afin qu’A&B Technologies puisse répondre à ma demande.','checkbox',true]]},
    {id:'files',title:'Documents utiles',lead:'Vous pouvez joindre logo, PDF, captures, maquettes ou tout document qui aide à comprendre votre projet.',special:'files'},
    {id:'summary',title:'Voici ce que nous avons compris',lead:'Relisez votre demande. Vous pouvez revenir à toute étape avant l’envoi.',special:'summary'}
  ];
  const activeSteps = () => steps.filter(s => !s.when || s.when());
  const value = (key) => state.answers[key] ?? '';
  const input = ([key,label,type,required=false,options]) => {
    const v = value(key), req = required ? ' required' : '', full = type === 'textarea' || type === 'checkbox' ? ' full' : '';
    if(type === 'checkbox') return `<div class="field${full}"><label class="choice"><input data-key="${key}" type="checkbox"${v ? ' checked':''}${req}> <span>${esc(label)}</span></label></div>`;
    let control;
    if(type === 'textarea') control = `<textarea data-key="${key}"${req}>${esc(v)}</textarea>`;
    else if(type === 'select') control = `<select data-key="${key}"${req}><option value="">Sélectionnez…</option>${options.map(o=>`<option${v===o?' selected':''}>${esc(o)}</option>`).join('')}</select>`;
    else control = `<input data-key="${key}" type="${type}" value="${esc(v)}"${req}>`;
    return `<div class="field${full}"><label>${esc(label)}${required?' *':''}</label>${control}</div>`;
  };
  const choices = ([key,values,required]) => `<div class="field full"><label>${key==='request_types'?'Votre demande':'Choisissez tout ce qui s’applique'}${required?' *':''}</label><div class="choices">${values.map(o=>`<label class="choice"><input type="checkbox" data-choice="${key}" value="${esc(o)}" ${(value(key)||[]).includes(o)?'checked':''}>${esc(o)}</label>`).join('')}</div></div>`;
  const special = (kind) => {
    if(kind==='references') return `<div class="field full"><label>Sites de référence</label><p class="hint">URL, ce que vous appréciez, ce que vous voulez éviter.</p><div id="references">${renderReferences()}</div><button class="add" type="button" data-add-reference>+ Ajouter une référence</button></div>`;
    if(kind==='priorities') return `<div class="field full"><label>Fonctionnalités</label><div class="priorities">${opts.features.map(f=>`<div class="repeater-row"><span>${esc(f)}</span><select data-priority="${esc(f)}"><option>Je ne sais pas</option>${['Indispensable','Souhaitée','Peut attendre'].map(x=>`<option ${(value('feature_priorities')[f]||'')===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div></div>`;
    if(kind==='branches') { let html=''; if(has('Site e-commerce')) html += `<div class="field full"><label>E-commerce</label><div class="fields">${[['product_count','Nombre approximatif de produits','text'],['product_kind','Produits vendus','select',false,['Physiques','Digitaux','Services','Un mélange']],['payments','Moyens de paiement souhaités','text'],['delivery','Livraison, retrait ou suivi de commande','textarea']].map(input).join('')}</div></div>`; if(has('Réservation')) html += `<div class="field full"><label>Réservation et rendez-vous</label><div class="fields">${[['booking_type','Quel type de réservation ?','text'],['booking_duration','Durée habituelle','text'],['booking_mode','Format','select',false,['En ligne','En présentiel','Les deux']],['booking_rules','Créneaux, rappels, annulations, paiement…','textarea']].map(input).join('')}</div></div>`; if(has('Application mobile')) html += `<div class="field full"><label>Application mobile</label><div class="fields">${[['mobile_platforms','Plateformes','select',false,['Android','iOS','Les deux']],['mobile_features','Besoins spécifiques : notifications, photo, GPS, QR, hors connexion…','textarea'],['mobile_web','Une version web est-elle aussi prévue ?','select',false,['Oui','Non','Je ne sais pas']]].map(input).join('')}</div></div>`; return html; }
    if(kind==='files') return `<div class="field full"><label>Ajouter des fichiers</label><p class="hint">PDF, JPG, PNG, WebP, DOC ou DOCX — 10 Mo maximum par fichier. Les documents restent privés.</p><input id="fileInput" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx"><div id="fileList"></div></div>`;
    if(kind==='summary') return `<div class="summary" id="summary"></div>`;
    return '';
  };
  const renderReferences = () => (value('references')||[]).map((r,i)=>`<div class="repeater" data-ref="${i}"><div class="repeater-row"><input data-ref-field="url" placeholder="https://…" value="${esc(r.url||'')}"><input data-ref-field="like" placeholder="Ce que vous aimez" value="${esc(r.like||'')}"><button type="button" class="remove" data-remove-ref="${i}">Retirer</button></div><input data-ref-field="avoid" placeholder="Ce que vous n’aimez pas" value="${esc(r.avoid||'')}"></div>`).join('') || '<p class="hint">Aucune référence ajoutée.</p>';
  function render(){ const active=activeSteps(); state.step=Math.min(state.step,active.length-1); const step=active[state.step]; $('#stepCount').textContent=`Étape ${state.step+1} sur ${active.length}`; $('#progressBar').style.width=`${((state.step+1)/active.length)*100}%`; $('#previous').classList.toggle('hidden',state.step===0); $('#next').textContent=step.id==='summary'?'Confirmer et envoyer ma demande':'Continuer'; $('#stepContent').innerHTML=`<h2 class="step-title">${step.title}</h2><p class="step-lead">${step.lead}</p><div class="fields">${step.choices?choices(step.choices):''}${(step.fields||[]).map(input).join('')}${step.special?special(step.special):''}</div>`; if(step.special==='files') renderFiles(); if(step.special==='summary') renderSummary(); $('#formError').textContent=''; bind(); }
  function bind(){ $('#stepContent').querySelectorAll('[data-key]').forEach(el=>el.addEventListener('input',()=>{state.answers[el.dataset.key]=el.type==='checkbox'?el.checked:el.value; save();})); $('#stepContent').querySelectorAll('[data-choice]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.choice; state.answers[k]=[...document.querySelectorAll(`[data-choice="${k}"]:checked`)].map(x=>x.value); save();})); $('#stepContent').querySelectorAll('[data-priority]').forEach(el=>el.addEventListener('change',()=>{state.answers.feature_priorities ||= {};state.answers.feature_priorities[el.dataset.priority]=el.value;save();})); $('[data-add-reference]')?.addEventListener('click',()=>{state.answers.references ||= [];state.answers.references.push({});render();save();}); $('#stepContent').querySelectorAll('[data-remove-ref]').forEach(el=>el.addEventListener('click',()=>{state.answers.references.splice(Number(el.dataset.removeRef),1);render();save();})); $('#references')?.addEventListener('input',(e)=>{const box=e.target.closest('[data-ref]');if(!box)return; state.answers.references[Number(box.dataset.ref)][e.target.dataset.refField]=e.target.value;save();}); $('#fileInput')?.addEventListener('change',addFiles); }
  function save(){localStorage.setItem(DRAFT_KEY,JSON.stringify({answers:state.answers}));$('#saveState').textContent='Brouillon enregistré';}
  function addFiles(e){for(const file of e.target.files){if(!ALLOWED_TYPES.includes(file.type)||file.size>MAX_FILE_SIZE){$('#formError').textContent=`« ${file.name} » n’est pas accepté (format autorisé ou 10 Mo maximum).`;continue;}if(!state.files.some(x=>x.name===file.name&&x.size===file.size))state.files.push(file);}renderFiles();}
  function renderFiles(){const el=$('#fileList');if(el)el.innerHTML=state.files.map((f,i)=>`<div class="choice" style="margin-top:8px"><span>${esc(f.name)} <small>(${Math.ceil(f.size/1024)} Ko)</small></span><button type="button" class="remove" data-remove-file="${i}">Retirer</button></div>`).join('');el?.querySelectorAll('[data-remove-file]').forEach(b=>b.onclick=()=>{state.files.splice(+b.dataset.removeFile,1);renderFiles();});}
  function renderSummary(){const a=state.answers, name=[a.first_name,a.last_name].filter(Boolean).join(' ')||'—';$('#summary').innerHTML=[['Client',`${name}${a.company_name?' · '+a.company_name:''}\n${a.email||''}`],['Projet',(a.request_types||[]).join(', ')||'—'],['Objectifs',(a.objectives||[]).join(', ')||a.current_problem||'—'],['Cible',(a.audience||[]).join(', ')||'—'],['Design',(a.design_style||[]).join(', ')||'—'],['Pages',(a.pages||[]).join(', ')||'—'],['Fonctionnalités',Object.entries(a.feature_priorities||{}).filter(([,v])=>v!=='Je ne sais pas').map(([k,v])=>`${k} (${v})`).join(', ')||'—'],['Vision',a.vision||'—'],['Budget et délai',`${a.budget||'—'} · ${a.timeline||'—'}`],['Documents',state.files.map(f=>f.name).join(', ')||'Aucun']].map(([h,p])=>`<article><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join('');}
  function validate(){const active=activeSteps(),step=active[state.step], fields=$('#stepContent').querySelectorAll('[required]');for(const f of fields){if((f.type==='checkbox'&&!f.checked)||!f.checkValidity()){f.focus();$('#formError').textContent='Veuillez renseigner les informations obligatoires avant de continuer.';return false;}}if(step.choices?.[2] && !(value(step.choices[0])||[]).length){$('#formError').textContent='Veuillez sélectionner au moins une option.';return false;}return true;}
  async function uploadFiles(requestId){if(!state.files.length)return[];const uploads=[];for(const file of state.files){const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120);const path=`${requestId}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('project-documents').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(`Impossible d’envoyer « ${file.name} » : ${error.message}`);uploads.push({path,name:file.name,type:file.type,size:file.size});}return uploads;}
  async function submit(){if(!supabase){$('#formError').textContent='Le configurateur n’est pas encore relié à sa base sécurisée. Aucun envoi n’a été effectué.';return;}state.sending=true;$('#next').disabled=true;$('#next').textContent='Envoi sécurisé…';try{const identity=Object.fromEntries(['first_name','last_name','company_name','email','phone','whatsapp','country','city','preferred_language'].map(k=>[k,value(k)]));const {data,error}=await supabase.rpc('submit_project_request',{payload:{identity,answers:state.answers,consent:!!state.answers.consent}});if(error)throw error;const request=Array.isArray(data)?data[0]:data; if(!request?.id)throw new Error('La référence de demande est introuvable.');const documents=await uploadFiles(request.id);if(documents.length){const {error:docError}=await supabase.rpc('attach_request_documents',{target_request_id:request.id,documents});if(docError)throw docError;}if(config.notificationFunctionUrl){fetch(config.notificationFunctionUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:request.id,reference:request.reference})}).catch(()=>{});}localStorage.removeItem(DRAFT_KEY);$('#reference').textContent=request.reference;$('#wizard').classList.add('hidden');$('#confirmation').classList.remove('hidden');}catch(error){$('#formError').textContent=`Aucun envoi de confirmation n’a été affiché. Votre demande n’est peut-être pas complète : ${error.message||'erreur réseau'}`;}finally{state.sending=false;$('#next').disabled=false;$('#next').textContent='Confirmer et envoyer ma demande';}}
  $('#previous').onclick=()=>{state.step--;render();window.scrollTo({top:0,behavior:'smooth'});};$('#next').onclick=async()=>{if(!validate())return;if(activeSteps()[state.step].id==='summary')return submit();state.step++;render();window.scrollTo({top:0,behavior:'smooth'});};
  if(!supabase){const n=$('#setupWarning');n.textContent='Configuration en attente : les réponses peuvent être préparées et sauvegardées ici, mais aucun envoi n’est possible tant que Supabase n’est pas configuré.';n.classList.remove('hidden');}
  render();
})();
