import {cleanEmail,cleanPhone,cleanText,cleanUrl,clientIp,json,sha256} from '../../_lib/util.js';
import {corsHeaders,isAllowedRequestOrigin,optionsResponse,readJson} from '../../_lib/http.js';
import {processAuditNotifications} from '../../_lib/notifications.js';

const OBJECTIVES=new Set(['obtenir_plus_de_clients','ameliorer_visibilite','moderniser_image','ameliorer_site','mieux_apparaitre_google','developper_reseaux','vendre_en_ligne','outils_numeriques','autre']);
const PROBLEMS=new Set(['peu_visible','site_inadapte','manque_clients','reseaux_inactifs','image_vieillissante','difficile_a_gerer','aucune_presence','autre']);
const NETWORKS=['website','google','instagram','facebook','tiktok','linkedin','other'];
export function onRequestOptions({request}){return optionsResponse(request)}
export async function onRequestPost(context){const{request,env}=context,headers=corsHeaders(request);if(!isAllowedRequestOrigin(request))return json({error:'Origine non autorisée.'},403);
  try{const body=await readJson(request,65536);if(cleanText(body.websiteConfirm,100))return json({accepted:true},202,headers);if(typeof body.submissionId!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(body.submissionId))throw new Error('Identifiant de soumission invalide.');const existing=await env.AUDIT_DB.prepare('SELECT id,reference FROM audit_requests WHERE submission_key=?').bind(body.submissionId).first();if(existing)return json({success:true,reference:existing.reference,duplicate:true},200,headers);
    const p=body.payload||{},firstName=cleanText(p.firstName,100,true),lastName=cleanText(p.lastName,100,true),email=cleanEmail(p.email),phone=cleanPhone(p.phone),companyName=cleanText(p.companyName,180,true),activity=cleanText(p.activity,180,true),city=cleanText(p.city,180),companyDescription=cleanText(p.companyDescription,1500),mainObjective=cleanText(p.mainObjective,80,true),objectiveDetails=cleanText(p.objectiveDetails,1000,mainObjective==='autre'),mainProblem=cleanText(p.mainProblem,80,true),problemDetails=cleanText(p.problemDetails,2000),additionalInformation=cleanText(p.additionalInformation,3000);if(!OBJECTIVES.has(mainObjective))throw new Error('Objectif non reconnu.');if(!PROBLEMS.has(mainProblem))throw new Error('Problème principal non reconnu.');if(p.consent!==true)throw new Error('Votre accord est nécessaire pour transmettre la demande.');const inputPresence=p.digitalPresence&&typeof p.digitalPresence==='object'?p.digitalPresence:{},digitalPresence={};for(const key of NETWORKS){const source=inputPresence[key]&&typeof inputPresence[key]==='object'?inputPresence[key]:{},present=source.present===true,url=present?cleanUrl(source.url):'';if(present&&!url)throw new Error(`L’URL de ${key==='website'?'votre site internet':key==='google'?'Google / Google Maps':key} est requise.`);digitalPresence[key]={present,url}}if(Array.isArray(p.additionalLinks)&&p.additionalLinks.length>10)throw new Error('Ajoutez au maximum 10 liens complémentaires.');const additionalLinks=Array.isArray(p.additionalLinks)?p.additionalLinks.map(cleanUrl).filter(Boolean):[];
    const fingerprint=await sha256(`${clientIp(request)}|${env.AUDIT_RATE_LIMIT_SALT}`),since=new Date(Date.now()-3600000).toISOString(),recent=await env.AUDIT_DB.prepare('SELECT COUNT(*) AS total FROM audit_submission_limits WHERE fingerprint_hash=? AND created_at>=?').bind(fingerprint,since).first();if(Number(recent?.total||0)>=5)return json({error:'Trop de demandes récentes. Réessayez dans une heure.'},429,headers);const now=new Date().toISOString(),year=new Date().getUTCFullYear();await env.AUDIT_DB.prepare('INSERT INTO audit_submission_limits(fingerprint_hash,created_at) VALUES(?,?)').bind(fingerprint,now).run();const counter=await env.AUDIT_DB.prepare('INSERT INTO audit_reference_counters(year,last_number) VALUES(?,1) ON CONFLICT(year) DO UPDATE SET last_number=last_number+1 RETURNING last_number').bind(year).first();const reference=`AUD-${year}-${String(counter.last_number).padStart(6,'0')}`,id=crypto.randomUUID(),answers={identity:{firstName,lastName,email,phone},company:{companyName,activity,city,companyDescription},digitalPresence,additionalLinks,objective:{mainObjective,objectiveDetails},problem:{mainProblem,problemDetails},additional:{additionalInformation,consent:true}},adminDelivery=crypto.randomUUID(),clientDelivery=crypto.randomUUID();
    try{await env.AUDIT_DB.batch([env.AUDIT_DB.prepare('INSERT INTO audit_requests(id,reference,submission_key,status,first_name,last_name,email,phone,company_name,activity,city,company_description,digital_presence,main_objective,objective_details,main_problem,problem_details,additional_information,answers,consent_at,submitted_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,reference,body.submissionId,'NEW',firstName,lastName,email,phone,companyName,activity,city||null,companyDescription||null,JSON.stringify(digitalPresence),mainObjective,objectiveDetails||null,mainProblem,problemDetails||null,additionalInformation||null,JSON.stringify(answers),now,now,now,now),env.AUDIT_DB.prepare('INSERT INTO audit_status_history(audit_id,old_status,new_status,actor,created_at) VALUES(?,NULL,?,?,?)').bind(id,'NEW','system',now),env.AUDIT_DB.prepare('INSERT INTO audit_notification_deliveries(id,audit_id,notification_type,recipient,status,idempotency_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(adminDelivery,id,'admin',env.ADMIN_EMAIL,'pending',crypto.randomUUID(),now,now),env.AUDIT_DB.prepare('INSERT INTO audit_notification_deliveries(id,audit_id,notification_type,recipient,status,idempotency_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(clientDelivery,id,'client',email,'pending',crypto.randomUUID(),now,now)])}catch(error){const duplicate=await env.AUDIT_DB.prepare('SELECT reference FROM audit_requests WHERE submission_key=?').bind(body.submissionId).first();if(duplicate)return json({success:true,reference:duplicate.reference,duplicate:true},200,headers);throw error}
    context.waitUntil(processAuditNotifications(env,id).catch(()=>{}));return json({success:true,reference,notifications:[{type:'admin',status:'pending'},{type:'client',status:'pending'}]},201,headers)
  }catch(error){return json({error:error instanceof Error?error.message:'Demande invalide.'},error?.status||400,headers)}}
