$ErrorActionPreference='Stop';$repo='bayaya-devi/A-B-TECHNOLOGIES'
function Read-RepoFile($path){$item=(gh api "repos/$repo/contents/$path")|ConvertFrom-Json;@{item=$item;text=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(($item.content -replace '\s','')))}}
function Write-RepoFile($path,$item,$text,$message){$body=@{message=$message;content=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($text));sha=$item.sha;branch='main'}|ConvertTo-Json -Compress;$body|gh api "repos/$repo/contents/$path" --method PUT --input -|Out-Null}

$source=Read-RepoFile 'crm.js';$text=$source.text
$anchor="function renderDetail(){const r=current.r;"
$helpers=@'
function nextCommercialAction(status){return({nouvelle_demande:'Qualifier la demande',new:'Qualifier la demande',a_contacter:'Contacter le client',qualification:'Completer la qualification',qualified:'Proposer un rendez-vous',contacte:'Proposer un rendez-vous',contacted:'Proposer un rendez-vous',rdv_propose:'Obtenir le choix du creneau',rdv_programme:'Preparer le rendez-vous',devis_a_preparer:'Preparer le devis',devis_envoye:'Suivre la decision du client',devis_accepte:'Demarrer le projet',projet_accepte:'Demarrer le projet',devis_refuse:'Cloturer ou requalifier',perdu:'Archiver le dossier'}[status]||'Examiner le dossier')}
function money(q){return q?`${Number(q.amount).toLocaleString('fr-FR')} ${q.currency}`:'Aucun devis'}
function commercialOverview(){const r=current.r,q=current.quotes[0],appt=current.appointments.find(a=>a.status==='confirmed')||current.appointments.find(a=>a.status==='proposed'),sent=current.communications.filter(c=>c.status==='sent').length,failed=current.communications.filter(c=>c.status==='failed').length;const rdv=appt?(appt.status==='confirmed'?`Confirme le ${fmt(appt.confirmed_slot||appt.starts_at)}`:`${appt.appointment_slots.length} creneau(x) propose(s)`):'Aucun rendez-vous';return `<section class="commercial-overview"><div class="summary-card"><span>Client</span><b>${esc(r.first_name)} ${esc(r.last_name)}</b><small>${esc(r.company_name||r.email)}</small></div><div class="summary-card"><span>Demande</span><b>${esc(val(r.request_types))}</b><small>${esc(val(r.summary?.vision)).slice(0,110)}</small></div><div class="summary-card"><span>Relation commerciale</span>${badge(r.status)}</div><div class="summary-card next-card"><span>Prochaine action</span><b>${nextCommercialAction(r.status)}</b></div><div class="summary-card"><span>Rendez-vous</span><b>${esc(rdv)}</b></div><div class="summary-card"><span>Devis</span><b>${esc(q?q.reference:'Aucun devis')}</b><small>${esc(q?money(q)+' - '+q.status:'A preparer selon qualification')}</small></div><div class="summary-card"><span>Emails</span><b>${sent} envoye(s)</b><small>${failed?failed+' en echec':'Aucun echec'}</small></div></section>`}
function renderDetail(){const r=current.r;
'@
if(-not $text.Contains('function commercialOverview()')){$text=$text.Replace($anchor,$helpers.TrimEnd("`r","`n"))}
$text=$text.Replace('</div></div><section class="actions-box">','</div></div>${commercialOverview()}<section class="actions-box">')
$text=$text.Replace("['documents','Documents']","['documents','Documents ('+(current.docs.length+current.quotes.length)+')']").Replace("['exchanges','Échanges']","['exchanges','Échanges ('+current.communications.length+')']")
$appointment=@'
function appointmentCards(){if(!current.appointments.length)return '<div class="empty">Aucun rendez-vous.</div>';return current.appointments.map(a=>{const confirmed=a.status==='confirmed',headline=confirmed?`Confirme le ${fmt(a.confirmed_slot||a.starts_at)}`:`${a.appointment_slots.length} creneau(x) propose(s)`,slots=a.appointment_slots.map(s=>`${fmt(s.starts_at)} - ${s.status}`).join(' / ');return `<div class="document appointment-card"><div><div>${badge(a.status)} <b>${esc(a.mode||'Rendez-vous')} - ${a.duration_minutes||30} min</b></div><strong>${esc(headline)}</strong><small class="muted">${esc(slots)}</small></div><div>${a.status==='proposed'?a.appointment_slots.map(s=>`<button class="secondary" data-confirm-slot="${s.id}" data-appointment="${a.id}" data-start="${s.starts_at}">Confirmer ${fmt(s.starts_at)}</button>`).join(' '):''}</div></div>`}).join('')}
function renderTab
'@
$text=[regex]::Replace($text,'function appointmentCards\(\)\{.*?\}\r?\nfunction renderTab',$appointment.TrimEnd("`r","`n"),[Text.RegularExpressions.RegexOptions]::Singleline)
$text=$text.Replace('items.push({name:q.filename,url:x.data?.signedUrl,type:`Devis ${q.reference} · ${q.status}`,quote:q})','items.push({name:q.filename,url:x.data?.signedUrl,type:`Devis ${q.reference} - ${money(q)} - ${q.status}${q.validity_date?` - valide jusqu au ${new Date(q.validity_date).toLocaleDateString(''fr-FR'')}`:''''}`,quote:q})')
$text=$text.Replace("body:x.body,id:x.id,type:x.type,error:x.error_message","body:x.body,id:x.id,type:x.type,error:x.error_message,recipient:x.recipient_email,provider:x.provider")
$text=$text.Replace("${e.type?' · '+esc(e.type):''}</small>","${e.type?' · '+esc(e.type):''}${e.recipient?' · vers '+esc(e.recipient):''}</small>")
Write-RepoFile 'crm.js' $source.item $text 'ux: clarify commercial dossier priorities'

$cssSource=Read-RepoFile 'crm.css';$css=$cssSource.text
if(-not $css.Contains('.commercial-overview')){$css += @'

.commercial-overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:18px 0}.summary-card{min-height:92px;border:1px solid var(--line);border-radius:11px;padding:12px;background:#fff;display:flex;flex-direction:column;gap:5px}.summary-card>span{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}.summary-card>b{font:700 14px Manrope}.summary-card small{color:var(--muted);display:block}.summary-card .badge{align-self:flex-start}.next-card{background:#edf4ff;border-color:#b9cdf5}.next-card b{color:#194ebf}.appointment-card>div:first-child{display:flex;flex-direction:column;gap:5px}.appointment-card>div:last-child{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:5px}@media(max-width:1180px){.commercial-overview{grid-template-columns:repeat(3,1fr)}}@media(max-width:850px){.commercial-overview{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.commercial-overview{grid-template-columns:1fr}}
'@}
Write-RepoFile 'crm.css' $cssSource.item $css 'ux: style commercial dossier summary'
