const url=process.env.SUPABASE_URL,anon=process.env.SUPABASE_ANON_KEY,service=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!anon||!service)throw new Error('Variables Supabase manquantes');
const stamp=Date.now(),adminEmail=`ab.crm.admin.${stamp}@example.com`,userEmail=`ab.crm.user.${stamp}@example.com`,password=`Crm-${crypto.randomUUID()}!`;
let adminId,userId,requestId,leadId,quotePath;const results=[];
const headers=(key,token=key,extra={})=>({apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extra});
async function call(path,options={},key=service,token=key){const response=await fetch(`${url}${path}`,{...options,headers:headers(key,token,options.headers)});const text=await response.text();let data=text;try{data=text?JSON.parse(text):null}catch{}return{ok:response.ok,status:response.status,data}}
function check(name,ok,detail=''){results.push({name,passed:Boolean(ok),detail});if(!ok)throw new Error(`${name}: ${detail}`)}
async function invoke(token,body){return call('/functions/v1/send-client-email',{method:'POST',body:JSON.stringify(body)},anon,token)}
try{
  const createAdmin=await call('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email:adminEmail,password,email_confirm:true})});adminId=createAdmin.data?.id;check('création admin test',createAdmin.ok&&adminId,`HTTP ${createAdmin.status}`);
  const link=await call('/rest/v1/app_admins',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:adminId,display_name:'CRM Test'})});check('liaison app_admins',link.ok,`HTTP ${link.status}`);
  const createUser=await call('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email:userEmail,password,email_confirm:true})});userId=createUser.data?.id;check('création non-admin test',createUser.ok&&userId,`HTTP ${createUser.status}`);
  const adminLogin=await call('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:adminEmail,password})},anon,anon);const adminToken=adminLogin.data?.access_token;check('connexion admin test',adminLogin.ok&&adminToken,`HTTP ${adminLogin.status}`);
  const userLogin=await call('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:userEmail,password})},anon,anon);const userToken=userLogin.data?.access_token;check('connexion non-admin test',userLogin.ok&&userToken,`HTTP ${userLogin.status}`);
  const payload={submission_id:crypto.randomUUID(),consent:true,identity:{first_name:'TEST',last_name:'Mini CRM',company_name:'A&B TEST CRM',email:'aetbconseil@gmail.com',phone:'+22900000000',whatsapp:'+22900000000',country:'Bénin',city:'Cotonou',preferred_language:'français'},answers:{request_types:['Site vitrine'],objectives:['Test CRM réel'],vision:'Validation complète du mini CRM',budget:'500 000 – 1 000 000 FCFA',timeline:'1 mois',complexity:'Intermédiaire'}};
  const submitted=await call('/rest/v1/rpc/submit_project_request',{method:'POST',body:JSON.stringify({payload})},anon,anon);requestId=submitted.data?.[0]?.id;const reference=submitted.data?.[0]?.reference;check('dossier test créé',submitted.ok&&requestId&&/^AB-\d{4}-\d{6}$/.test(reference),reference||`HTTP ${submitted.status}`);
  const project=await call(`/rest/v1/project_requests?id=eq.${requestId}&select=id,lead_id,status`);leadId=project.data?.[0]?.lead_id;check('demande source de vérité',project.data?.length===1&&leadId,project.data?.[0]?.status);
  const publicComms=await call('/rest/v1/communications?select=id',{},anon,anon);check('RLS communications public',publicComms.ok&&publicComms.data.length===0,`lignes=${publicComms.data?.length}`);
  const nonAdminQuotes=await call('/rest/v1/quotes?select=id',{},anon,userToken);check('RLS devis non-admin',nonAdminQuotes.ok&&nonAdminQuotes.data.length===0,`lignes=${nonAdminQuotes.data?.length}`);
  const forbidden=await invoke(userToken,{requestId,type:'general_email',subject:'Refus',body:'Refus',idempotencyKey:crypto.randomUUID()});check('Edge Function refuse non-admin',forbidden.status===403,`HTTP ${forbidden.status}`);
  const generalKey=crypto.randomUUID();const general=await invoke(adminToken,{requestId,type:'general_email',subject:`TEST CRM — Email libre ${reference}`,body:`Bonjour TEST,\n\nEmail libre réel pour ${reference}.\n\nA&B Technologies`,idempotencyKey:generalKey});check('email libre envoyé',general.ok&&general.data?.communication?.status==='sent',general.data?.error||`HTTP ${general.status}`);
  const duplicate=await invoke(adminToken,{requestId,type:'general_email',subject:'Ne doit pas partir',body:'Doublon',idempotencyKey:generalKey});check('double envoi empêché',duplicate.ok&&duplicate.data?.idempotent===true,JSON.stringify(duplicate.data));
  const slot1=new Date(Date.now()+86400000).toISOString(),slot2=new Date(Date.now()+172800000).toISOString();const appointment=await invoke(adminToken,{requestId,type:'appointment_proposal',subject:`TEST CRM — Rendez-vous ${reference}`,body:`Bonjour TEST,\n\nCréneaux proposés pour ${reference}.\n\nA&B Technologies`,idempotencyKey:crypto.randomUUID(),appointment:{mode:'Visio',durationMinutes:45,notes:'Test CRM',slots:[{startsAt:slot1},{startsAt:slot2}]}});check('proposition RDV envoyée',appointment.ok&&appointment.data?.communication?.status==='sent',appointment.data?.error||`HTTP ${appointment.status}`);
  const appts=await call(`/rest/v1/appointments?request_id=eq.${requestId}&select=id,status,mode,duration_minutes,appointment_slots(*)`,{},anon,adminToken);check('RDV et créneaux enregistrés',appts.data?.length===1&&appts.data[0].status==='proposed'&&appts.data[0].appointment_slots.length===2,JSON.stringify(appts.data));
  const info=await invoke(adminToken,{requestId,type:'information_request',subject:`TEST CRM — Informations ${reference}`,body:'Bonjour TEST,\n\nMerci de transmettre votre logo et vos contenus.\n\nA&B Technologies',idempotencyKey:crypto.randomUUID()});check('demande informations envoyée',info.ok&&info.data?.communication?.status==='sent',info.data?.error||`HTTP ${info.status}`);
  quotePath=`${requestId}/${crypto.randomUUID()}-devis-test.pdf`;const pdf=new TextEncoder().encode('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');const upload=await fetch(`${url}/storage/v1/object/crm-documents/${quotePath}`,{method:'POST',headers:headers(anon,adminToken,{'Content-Type':'application/pdf','x-upsert':'false'}),body:pdf});check('PDF devis stocké en privé',upload.ok,`HTTP ${upload.status}`);
  const quoteCreate=await call('/rest/v1/quotes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({project_request_id:requestId,lead_id:leadId,amount:750000,currency:'XOF',estimated_duration:'4 semaines',validity_date:new Date(Date.now()+1209600000).toISOString().slice(0,10),storage_path:quotePath,filename:'devis-test.pdf',created_by:adminId})},anon,adminToken);const quote=quoteCreate.data?.[0];check('devis et référence créés',quoteCreate.ok&&/^DEV-AB-\d{4}-\d{6}$/.test(quote?.reference),quote?.reference||`HTTP ${quoteCreate.status}`);
  const quoteSend=await invoke(adminToken,{requestId,type:'quote',quoteId:quote.id,subject:`TEST CRM — Devis ${quote.reference}`,body:`Bonjour TEST,\n\nVeuillez trouver le devis ${quote.reference} en pièce jointe.\n\nA&B Technologies`,idempotencyKey:crypto.randomUUID()});check('devis envoyé avec PDF',quoteSend.ok&&quoteSend.data?.communication?.status==='sent',quoteSend.data?.error||`HTTP ${quoteSend.status}`);
  const quoteAfter=await call(`/rest/v1/quotes?id=eq.${quote.id}&select=status,sent_at`,{},anon,adminToken);check('statut devis envoyé',quoteAfter.data?.[0]?.status==='sent'&&quoteAfter.data[0].sent_at,JSON.stringify(quoteAfter.data));
  const follow=await invoke(adminToken,{requestId,type:'follow_up',subject:`TEST CRM — Relance ${reference}`,body:'Bonjour TEST,\n\nNous revenons vers vous concernant votre devis.\n\nA&B Technologies',idempotencyKey:crypto.randomUUID()});check('relance envoyée',follow.ok&&follow.data?.communication?.status==='sent',follow.data?.error||`HTTP ${follow.status}`);
  const missingPath=`${requestId}/${crypto.randomUUID()}-absent.pdf`;const badQuote=await call('/rest/v1/quotes',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({project_request_id:requestId,lead_id:leadId,amount:1,currency:'XOF',storage_path:missingPath,filename:'absent.pdf',created_by:adminId})});const badQuoteId=badQuote.data?.[0]?.id;check('devis échec préparé',badQuote.ok&&badQuoteId,`HTTP ${badQuote.status}`);
  const failed=await invoke(adminToken,{requestId,type:'quote',quoteId:badQuoteId,subject:`TEST CRM — Échec contrôlé ${reference}`,body:'Ce message ne doit pas être envoyé.',idempotencyKey:crypto.randomUUID()});const failedId=failed.data?.communicationId;check('échec conservé',failed.status===502&&failedId,JSON.stringify(failed.data));
  const failedRow=await call(`/rest/v1/communications?id=eq.${failedId}&select=status,attempt_count,error_message`,{},anon,adminToken);check('communication failed réessayable',failedRow.data?.[0]?.status==='failed'&&failedRow.data[0].attempt_count===1&&failedRow.data[0].error_message,JSON.stringify(failedRow.data));
  const retry=await invoke(adminToken,{requestId,retryCommunicationId:failedId});const retryRow=await call(`/rest/v1/communications?id=eq.${failedId}&select=status,attempt_count`,{},anon,adminToken);check('retry enregistré sans perte demande',retry.status===502&&retryRow.data?.[0]?.status==='failed'&&retryRow.data[0].attempt_count===2,JSON.stringify(retryRow.data));
  const stillThere=await call(`/rest/v1/project_requests?id=eq.${requestId}&select=id,status`);check('demande intacte après échec',stillThere.data?.length===1,JSON.stringify(stillThere.data));
  const comms=await call(`/rest/v1/communications?project_request_id=eq.${requestId}&select=type,status,provider_message_id`,{},anon,adminToken);check('historique communications complet',comms.data.filter(x=>x.status==='sent').length===5&&comms.data.filter(x=>x.status==='failed').length===1,JSON.stringify(comms.data));
  const history=await call(`/rest/v1/project_status_history?request_id=eq.${requestId}&select=new_status`,{},anon,adminToken);check('historique statuts CRM',history.data.some(x=>x.new_status==='rdv_propose')&&history.data.some(x=>x.new_status==='devis_envoye'),JSON.stringify(history.data));
  const publicFile=await fetch(`${url}/storage/v1/object/crm-documents/${quotePath}`,{headers:{apikey:anon}});check('PDF privé refusé au public',!publicFile.ok,`HTTP ${publicFile.status}`);
  console.log(JSON.stringify({passed:results.filter(x=>x.passed).length,failed:0,reference,quoteReference:quote.reference,realEmailsSent:5,results},null,2));
}catch(error){console.error(JSON.stringify({passed:results.filter(x=>x.passed).length,failed:1,error:error.message,results},null,2));process.exitCode=1}
finally{
  if(quotePath)await call(`/storage/v1/object/crm-documents/${quotePath}`,{method:'DELETE'}).catch(()=>{});
  if(requestId)await call(`/rest/v1/project_requests?id=eq.${requestId}`,{method:'DELETE'}).catch(()=>{});
  if(leadId)await call(`/rest/v1/leads?id=eq.${leadId}`,{method:'DELETE'}).catch(()=>{});
  if(adminId)await call(`/auth/v1/admin/users/${adminId}`,{method:'DELETE'}).catch(()=>{});
  if(userId)await call(`/auth/v1/admin/users/${userId}`,{method:'DELETE'}).catch(()=>{});
}
